import type { ShipKind } from "./kinds";
import {
  PART_TYPES,
  type AttachPartDef,
  type AttachPointType,
  type GridPartDef,
  type PartCategory,
  type PartDef,
  type PartType,
} from "./types";

/** In the order a ship is built, which is the order the Parts panel lists. */
export const CATEGORIES: readonly { id: PartCategory; name: string }[] = [
  { id: "decks", name: "Decks" },
  { id: "cabins", name: "Cabins" },
  { id: "command", name: "Command" },
  { id: "funnels", name: "Funnels" },
  { id: "propulsion", name: "Propulsion" },
  { id: "masts", name: "Masts" },
  { id: "sails", name: "Sails" },
  { id: "lifeboats", name: "Lifeboat gear" },
  { id: "naval", name: "Naval" },
  { id: "weapons", name: "Cannons" },
  { id: "cargo", name: "Cargo" },
  { id: "lights", name: "Lights" },
  { id: "decor", name: "Decorations" },
];

/** Short "what's missing" lines for parts tiles with nowhere to go. */
export const ATTACH_NEEDS_LABELS: Record<AttachPointType, string> = {
  "funnel-mount": "Needs a deck block",
  "mast-mount": "No free mast spot",
  "davit-point": "Needs a deck edge",
  "boat-mount": "Needs a free davit",
  "large-funnel-mount": "Needs a 2×2 deck",
  "big-boat-mount": "Needs paired davits",
  "prop-mount": "No free prop spot",
  "rudder-mount": "Rudder spot taken",
  "heli-mount": "Needs a helipad",
  "freefall-mount": "No free stern spot",
  "edge-mount": "Needs a deck edge",
  "searchlight-mount": "Needs a bridge or mast",
  "nest-mount": "Needs a mast",
  "flag-mount": "Flag spot taken",
  "aerial-mount": "Needs a 2nd mast",
  "string-mount": "Needs 2 masts or funnels",
  "nav-mount": "Needs a bridge",
  "hull-light-mount": "No free hull spot",
  "sail-mount": "Needs a wooden mast",
  "masthead-mount": "Needs a wooden mast",
  "bow-mount": "No free bow spot",
};

export const ATTACH_POINT_LABELS: Record<AttachPointType, string> = {
  "funnel-mount": "deck block with nothing on top",
  "mast-mount": "mast mount",
  "davit-point": "boat-deck edge",
  "boat-mount": "davit",
  "large-funnel-mount": "2×2 of deck blocks with nothing on top",
  "big-boat-mount": "pair of side-by-side davits",
  "prop-mount": "propeller spot under the stern",
  "rudder-mount": "rudder spot under the stern",
  "heli-mount": "helipad with nothing on it",
  "freefall-mount": "freefall boat spot at the stern",
  "edge-mount": "boat-deck edge",
  "searchlight-mount": "bridge roof or mast top without a searchlight",
  "nest-mount": "mast without a crow's nest",
  "flag-mount": "flagpole spot at the stern",
  "aerial-mount": "mast with another mast to string wires to",
  "string-mount": "mast or funnel with another one to string lights to",
  "nav-mount": "bridge roof without navigation lights",
  "hull-light-mount": "spot on the hull below the waterline",
  "sail-mount": "free sail spot on a wooden mast",
  "masthead-mount": "top of a wooden mast",
  "bow-mount": "spot on the bow",
};

const PIRATE: ShipKind[] = ["pirate"];
/** Parts that make no sense on a wooden sailing ship. */
const NOT_PIRATE: ShipKind[] = ["liner", "cruise", "navy", "cargo"];

function woodMastDef(
  type: PartType,
  name: string,
  height: number,
  sailSlots: number,
  mass: number
): PartDef {
  return {
    type,
    kinds: PIRATE,
    category: "masts",
    name,
    description: `Wooden mast · ${sailSlots} sail spot${sailSlots === 1 ? "" : "s"} · bow, stern or on a deck block`,
    placement: "attach",
    attachTo: "mast-mount",
    mass,
    height,
    emptyHint: "Every mast spot is taken",
    exposes: "mast",
    hasCrowsNest: true,
    sailSlots,
  };
}

function sailDef(
  type: PartType,
  name: string,
  sailArea: number,
  height: number,
  extra: Partial<AttachPartDef> = {}
): PartDef {
  return {
    type,
    kinds: PIRATE,
    category: "sails",
    name,
    description: `Sail area ${sailArea} · more sail, more speed`,
    placement: "attach",
    attachTo: "sail-mount",
    mass: 0.05 * sailArea,
    height,
    sailArea,
    emptyHint: "Build a wooden mast with a free sail spot first",
    ...extra,
  };
}

/** The 4-wide bridge keeps the original `bridge` id so old saves still load. */
function bridgeDef(type: PartType, width: number): PartDef {
  return {
    type,
    kinds: NOT_PIRATE,
    category: "command",
    name: `Bridge · ${width} wide`,
    description: "Forward half, top of its stack",
    placement: "grid",
    role: "bridge",
    footprint: { x: 1, z: width },
    mass: 1,
    height: 1,
  };
}

/** A 1×1 deck item: sits directly on the main deck or a deck block. */
function decorDef(
  type: PartType,
  name: string,
  description: string,
  height: number
): GridPartDef {
  return {
    type,
    category: "decor",
    name,
    description: `${description} · on the deck or a deck block`,
    placement: "grid",
    role: "decor",
    footprint: { x: 1, z: 1 },
    mass: 0.05,
    height,
  };
}

export const CATALOG: Record<PartType, PartDef> = {
  "deck-1x1": {
    type: "deck-1x1",
    category: "decks",
    name: "Deck block 1×1",
    description: "Superstructure · stacks four high",
    placement: "grid",
    role: "deck",
    footprint: { x: 1, z: 1 },
    mass: 1,
    height: 1,
  },
  "deck-2x1": {
    type: "deck-2x1",
    category: "decks",
    name: "Deck block 2×1",
    description: "Superstructure · stacks four high",
    placement: "grid",
    role: "deck",
    footprint: { x: 2, z: 1 },
    mass: 1,
    height: 1,
  },
  "cabin-1st": {
    type: "cabin-1st",
    category: "cabins",
    name: "First-class cabins",
    description: "30 passengers",
    placement: "grid",
    role: "cabin",
    footprint: { x: 1, z: 1 },
    mass: 1,
    height: 1,
    passengers: { cabinClass: "first", count: 30 },
  },
  "cabin-2nd": {
    type: "cabin-2nd",
    category: "cabins",
    name: "Second-class cabins",
    description: "50 passengers",
    placement: "grid",
    role: "cabin",
    footprint: { x: 1, z: 1 },
    mass: 1,
    height: 1,
    passengers: { cabinClass: "second", count: 50 },
  },
  "cabin-3rd": {
    type: "cabin-3rd",
    category: "cabins",
    name: "Third-class berths",
    description: "120 passengers",
    placement: "grid",
    role: "cabin",
    footprint: { x: 1, z: 1 },
    mass: 1,
    height: 1,
    passengers: { cabinClass: "third", count: 120 },
  },
  "cabin-crew": {
    type: "cabin-crew",
    category: "cabins",
    name: "Crew quarters",
    description: "60 crew berths",
    placement: "grid",
    role: "cabin",
    footprint: { x: 1, z: 1 },
    mass: 1,
    height: 1,
    crewBerths: 60,
  },
  "bridge-3": bridgeDef("bridge-3", 3),
  bridge: bridgeDef("bridge", 4),
  "bridge-5": bridgeDef("bridge-5", 5),
  "bridge-6": bridgeDef("bridge-6", 6),
  "bridge-7": bridgeDef("bridge-7", 7),
  funnel: {
    type: "funnel",
    kinds: ["liner"],
    category: "funnels",
    name: "Funnel",
    description: "Smokestack · sits on a deck block · 40 stokers",
    placement: "attach",
    attachTo: "funnel-mount",
    mass: 2,
    height: 3.2,
    stokers: 40,
    power: 1,
    emptyHint: "Place a deck block with nothing on top of it first",
    exposes: "funnel",
    smoke: "small",
  },
  mast: {
    type: "mast",
    kinds: NOT_PIRATE,
    category: "masts",
    name: "Mast",
    description: "Bow, stern or on top of a deck block",
    placement: "attach",
    attachTo: "mast-mount",
    mass: 0.5,
    height: 7,
    emptyHint: "Every mast spot is taken",
    exposes: "mast",
    hasCrowsNest: true,
  },
  davit: {
    type: "davit",
    category: "lifeboats",
    name: "Davit",
    description: "Boat-deck edge, on any block",
    placement: "attach",
    attachTo: "davit-point",
    mass: 0.1,
    height: 1,
    emptyHint: "Build a block on an outer edge of the ship",
    exposes: "davit",
    holdsEdge: true,
  },
  "lifeboat-standard": {
    type: "lifeboat-standard",
    category: "lifeboats",
    name: "Lifeboat",
    description: "65 seats · hangs from a davit",
    placement: "attach",
    attachTo: "boat-mount",
    mass: 0.2,
    height: 0.4,
    seats: 65,
    emptyHint: "Every davit has a boat — add another davit",
  },
  "lifeboat-collapsible": {
    type: "lifeboat-collapsible",
    kinds: ["liner"],
    category: "lifeboats",
    name: "Collapsible lifeboat",
    description: "47 seats · hangs from a davit",
    placement: "attach",
    attachTo: "boat-mount",
    mass: 0.2,
    height: 0.4,
    seats: 47,
    emptyHint: "Every davit has a boat — add another davit",
  },
  "funnel-large": {
    type: "funnel-large",
    kinds: ["liner"],
    category: "funnels",
    name: "Large funnel",
    description: "Big smokestack · sits on a 2×2 of deck blocks · 75 stokers",
    placement: "attach",
    attachTo: "large-funnel-mount",
    mass: 4,
    height: 4.2,
    stokers: 75,
    power: 2,
    emptyHint: "Make a 2×2 of deck blocks with nothing on top",
    exposes: "funnel",
    smoke: "large",
  },
  "lifeboat-large": {
    type: "lifeboat-large",
    kinds: ["liner"],
    category: "lifeboats",
    name: "Large lifeboat",
    description: "150 seats · hangs between two davits",
    placement: "attach",
    attachTo: "big-boat-mount",
    mass: 0.4,
    height: 0.5,
    seats: 150,
    emptyHint: "Put two davits side by side on the same deck edge",
  },
  propeller: {
    type: "propeller",
    kinds: NOT_PIRATE,
    category: "propulsion",
    name: "Propeller",
    description: "Mounts under the stern · pushes the ship",
    placement: "attach",
    attachTo: "prop-mount",
    mass: 0.3,
    height: 0.5,
    emptyHint: "Every propeller spot is taken",
    propels: true,
  },
  rudder: {
    type: "rudder",
    category: "propulsion",
    name: "Rudder",
    description: "Under the stern · steers the ship",
    placement: "attach",
    attachTo: "rudder-mount",
    mass: 0.2,
    height: 0.9,
    emptyHint: "The rudder spot is taken",
    steers: true,
  },
  "turret-small": {
    type: "turret-small",
    kinds: ["navy"],
    category: "naval",
    name: "Gun turret",
    description: "Sits on a deck block · slowly turns",
    placement: "attach",
    attachTo: "funnel-mount",
    mass: 1,
    height: 0.9,
    emptyHint: "Place a deck block with nothing on top of it first",
  },
  "turret-large": {
    type: "turret-large",
    kinds: ["navy"],
    category: "naval",
    name: "Big gun turret",
    description: "Twin guns · sits on a 2×2 of deck blocks",
    placement: "attach",
    attachTo: "large-funnel-mount",
    mass: 2.5,
    height: 1.2,
    emptyHint: "Make a 2×2 of deck blocks with nothing on top",
  },
  "radar-mast": {
    type: "radar-mast",
    kinds: ["navy"],
    category: "naval",
    name: "Radar mast",
    description: "Bow, stern or on top of a deck block · spinning radar",
    placement: "attach",
    attachTo: "mast-mount",
    mass: 0.6,
    height: 6,
    emptyHint: "Every mast spot is taken",
    exposes: "mast",
  },
  helipad: {
    type: "helipad",
    kinds: ["navy"],
    category: "naval",
    name: "Helipad",
    description: "Flat pad on a 2×2 of deck blocks",
    placement: "attach",
    attachTo: "large-funnel-mount",
    mass: 1,
    height: 0.15,
    emptyHint: "Make a 2×2 of deck blocks with nothing on top",
    exposes: "helipad",
  },
  helicopter: {
    type: "helicopter",
    kinds: ["navy"],
    category: "naval",
    name: "Helicopter",
    description: "Lands on a helipad · spinning rotor",
    placement: "attach",
    attachTo: "heli-mount",
    mass: 0.4,
    height: 1,
    emptyHint: "Build a helipad first",
  },
  "rib-boat": {
    type: "rib-boat",
    kinds: ["navy"],
    category: "lifeboats",
    name: "RIB boat",
    description: "15 seats · hangs from a davit",
    placement: "attach",
    attachTo: "boat-mount",
    mass: 0.2,
    height: 0.4,
    seats: 15,
    emptyHint: "Every davit has a boat — add another davit",
  },
  container: {
    type: "container",
    kinds: ["cargo"],
    category: "cargo",
    name: "Container",
    description: "2 TEU · on the main deck or a hatch cover · stacks",
    placement: "grid",
    role: "cargo",
    footprint: { x: 2, z: 1 },
    mass: 0.6,
    height: 1,
    teu: 2,
  },
  "hatch-cover": {
    type: "hatch-cover",
    kinds: ["cargo"],
    category: "cargo",
    name: "Hatch cover",
    description: "Low 2×2 cover over the hold · containers stack on it",
    placement: "grid",
    role: "deck",
    footprint: { x: 2, z: 2 },
    carriesCargo: true,
    mass: 0.3,
    height: 0.3,
  },
  "cargo-crane": {
    type: "cargo-crane",
    kinds: ["cargo"],
    category: "cargo",
    name: "Cargo crane",
    description: "Sits on a deck block or hatch cover · the jib turns slowly",
    placement: "attach",
    attachTo: "funnel-mount",
    mass: 1,
    height: 2.6,
    emptyHint: "Place a deck block or hatch cover with nothing on top first",
  },
  "lifeboat-freefall": {
    type: "lifeboat-freefall",
    kinds: ["cargo"],
    category: "lifeboats",
    name: "Freefall lifeboat",
    description: "40 seats · slides off the stern",
    placement: "attach",
    attachTo: "freefall-mount",
    mass: 0.5,
    height: 1.2,
    seats: 40,
    emptyHint: "The freefall spot at the stern is taken",
  },
  "cabin-balcony": {
    type: "cabin-balcony",
    kinds: ["cruise"],
    category: "cabins",
    name: "Balcony cabins",
    description: "40 passengers · balconies on outward faces",
    placement: "grid",
    role: "cabin",
    footprint: { x: 1, z: 1 },
    mass: 1,
    height: 1,
    passengers: { cabinClass: "second", count: 40 },
  },
  pool: {
    type: "pool",
    kinds: ["cruise"],
    category: "decks",
    name: "Pool",
    description: "2×2 · sits on blocks or the main deck · nothing builds on it",
    placement: "grid",
    role: "amenity",
    footprint: { x: 2, z: 2 },
    mass: 1,
    height: 0.3,
  },
  waterslide: {
    type: "waterslide",
    kinds: ["cruise"],
    category: "decks",
    name: "Waterslide",
    description: "Sits on a deck block · curls down the side",
    placement: "attach",
    attachTo: "funnel-mount",
    mass: 0.5,
    height: 2.5,
    emptyHint: "Place a deck block with nothing on top of it first",
  },
  "climbing-wall": {
    type: "climbing-wall",
    kinds: ["cruise"],
    category: "decks",
    name: "Climbing wall",
    description: "Sits on a deck block · tall wall with holds",
    placement: "attach",
    attachTo: "funnel-mount",
    mass: 0.5,
    height: 1.8,
    emptyHint: "Place a deck block with nothing on top of it first",
  },
  "lifeboat-enclosed": {
    type: "lifeboat-enclosed",
    kinds: ["cruise"],
    category: "lifeboats",
    name: "Enclosed lifeboat",
    description: "150 seats · hangs from a davit",
    placement: "attach",
    attachTo: "boat-mount",
    mass: 0.3,
    height: 0.5,
    seats: 150,
    emptyHint: "Every davit has a boat — add another davit",
  },
  "raft-canister": {
    type: "raft-canister",
    kinds: ["cruise", "navy"],
    category: "lifeboats",
    name: "Life raft canister",
    description: "25 seats · sits on a boat-deck edge",
    placement: "attach",
    attachTo: "edge-mount",
    mass: 0.1,
    height: 0.4,
    seats: 25,
    emptyHint: "Build a block on an outer edge of the ship",
    holdsEdge: true,
  },
  "funnel-modern": {
    type: "funnel-modern",
    kinds: ["cruise", "navy", "cargo"],
    category: "funnels",
    name: "Modern funnel",
    description: "Raked diesel stack · sits on a deck block · no stokers",
    placement: "attach",
    attachTo: "funnel-mount",
    mass: 2,
    height: 3.2,
    power: 4,
    emptyHint: "Place a deck block with nothing on top of it first",
    exposes: "funnel",
    smoke: "small",
  },
  azipod: {
    type: "azipod",
    kinds: ["cruise"],
    category: "propulsion",
    name: "Azipod",
    description: "Steerable pod under the stern · propels and steers",
    placement: "attach",
    attachTo: "prop-mount",
    mass: 0.5,
    height: 0.7,
    emptyHint: "Every propeller spot is taken",
    propels: true,
    steers: true,
  },
  dome: {
    type: "dome",
    kinds: ["liner"],
    category: "decor",
    name: "Glass dome",
    description: "Grand Staircase dome · sits on a deck block",
    placement: "attach",
    attachTo: "funnel-mount",
    mass: 0.4,
    height: 1,
    emptyHint: "Place a deck block with nothing on top of it first",
  },
  searchlight: {
    type: "searchlight",
    category: "masts",
    name: "Searchlight",
    description: "On the bridge roof or near the top of a mast",
    placement: "attach",
    attachTo: "searchlight-mount",
    mass: 0.05,
    height: 0.4,
    emptyHint: "Build a bridge or a mast first",
  },
  "crows-nest": {
    type: "crows-nest",
    category: "masts",
    name: "Crow's nest",
    description: "Lookout basket partway up a mast",
    placement: "attach",
    attachTo: "nest-mount",
    mass: 0.1,
    height: 0.4,
    emptyHint: "Build a mast first",
  },
  "stern-flag": {
    type: "stern-flag",
    category: "decor",
    name: "Stern flag",
    description: "A flag that waves at the stern · takes your paint",
    placement: "attach",
    attachTo: "flag-mount",
    mass: 0.05,
    height: 1.5,
    emptyHint: "The stern already has a flag",
  },
  "wireless-aerial": {
    type: "wireless-aerial",
    kinds: ["liner"],
    category: "masts",
    name: "Wireless aerial",
    description: "Wires from a mast top to the nearest other mast",
    placement: "attach",
    attachTo: "aerial-mount",
    mass: 0.05,
    height: 0.1,
    emptyHint: "Build a second mast to string wires to",
  },
  deckchair: decorDef("deckchair", "Deck chair", "A seat for sunbathing", 0.4),
  bench: decorDef(
    "bench",
    "Bench",
    "A wooden deck bench · turns with rotation",
    0.45
  ),
  "deck-lamp": decorDef(
    "deck-lamp",
    "Deck lamp",
    "A lamp post for the evening",
    1
  ),
  "string-lights": {
    type: "string-lights",
    category: "lights",
    name: "String lights",
    description:
      "Party bulbs strung from a mast or funnel to the nearest other one",
    placement: "attach",
    attachTo: "string-mount",
    mass: 0.05,
    height: 0.1,
    emptyHint: "Build two masts or funnels to string lights between",
  },
  "nav-lights": {
    type: "nav-lights",
    category: "lights",
    name: "Navigation lights",
    description:
      "On the bridge roof · red on the port (left) side, green on the starboard (right) side, white on top",
    placement: "attach",
    attachTo: "nav-mount",
    mass: 0.05,
    height: 0.6,
    emptyHint: "Build a bridge first",
  },
  floodlight: {
    ...decorDef(
      "floodlight",
      "Floodlight",
      "A bright light on a pole that lights up the deck · turns with rotation",
      1
    ),
    category: "lights",
  },
  "underwater-light": {
    type: "underwater-light",
    category: "lights",
    name: "Underwater light",
    description: "Glows in the water beside the hull · sits on the hull side",
    placement: "attach",
    attachTo: "hull-light-mount",
    mass: 0.05,
    height: 0.2,
    emptyHint: "Every spot on the hull has a light",
  },
  ventilator: {
    ...decorDef(
      "ventilator",
      "Ventilator",
      "Curved cowl air scoop · turns with rotation",
      0.8
    ),
    kinds: ["liner"],
  },
  stairs: {
    ...decorDef(
      "stairs",
      "Stairs",
      "Climbs up against the deck or cabin block it faces",
      1
    ),
    climbsToFacedBlock: true,
  },
  "mast-wood-short": woodMastDef("mast-wood-short", "Short mast", 5, 1, 0.4),
  "mast-wood-tall": woodMastDef("mast-wood-tall", "Tall mast", 7, 2, 0.5),
  "mast-wood-main": woodMastDef("mast-wood-main", "Main mast", 9, 3, 0.6),
  "sail-square-small": sailDef(
    "sail-square-small",
    "Small square sail",
    2,
    1.2
  ),
  "sail-square": sailDef("sail-square", "Square sail", 3, 1.6),
  "sail-square-large": sailDef("sail-square-large", "Large square sail", 4, 2),
  "sail-jib": sailDef("sail-jib", "Jib", 2, 1.4, {
    attachTo: "bow-mount",
    allowedPointIds: ["jib"],
    emptyHint: "The jib spot at the bow is taken",
  }),
  "sail-lateen": sailDef("sail-lateen", "Lateen sail", 3, 1.6, {
    allowedPointIds: ["sail:0"],
    description: "Sail area 3 · triangular · on the lowest spot of a mast",
  }),
  "flag-jolly-roger": {
    type: "flag-jolly-roger",
    kinds: PIRATE,
    category: "decor",
    name: "Jolly Roger",
    description: "The pirate flag · flies from the top of a wooden mast",
    placement: "attach",
    attachTo: "masthead-mount",
    mass: 0.02,
    height: 0.8,
    emptyHint: "Build a wooden mast first",
  },
  "cannon-deck": {
    type: "cannon-deck",
    kinds: PIRATE,
    category: "weapons",
    name: "Deck cannon",
    description:
      "Counts toward your cannons · sits on a deck edge · tap to fire",
    placement: "attach",
    attachTo: "edge-mount",
    mass: 0.25,
    height: 0.4,
    cannons: 1,
    emptyHint: "Build a block on an outer edge of the ship",
    holdsEdge: true,
  },
  "cannon-chaser": {
    type: "cannon-chaser",
    kinds: PIRATE,
    category: "weapons",
    name: "Bow chaser",
    description: "A long gun in the bow · counts toward your cannons",
    placement: "attach",
    attachTo: "bow-mount",
    allowedPointIds: ["bowgun"],
    mass: 0.3,
    height: 0.4,
    cannons: 1,
    emptyHint: "The bow gun spot is taken",
  },
  "cannon-swivel": {
    type: "cannon-swivel",
    kinds: PIRATE,
    category: "weapons",
    name: "Swivel gun",
    description: "A small rail gun · just for show · tap to fire",
    placement: "attach",
    attachTo: "edge-mount",
    mass: 0.08,
    height: 0.4,
    emptyHint: "Build a block on an outer edge of the ship",
    holdsEdge: true,
  },
  "cabin-captain": {
    type: "cabin-captain",
    kinds: PIRATE,
    category: "cabins",
    name: "Captain's cabin",
    description: "20 crew berths · stern windows",
    placement: "grid",
    role: "cabin",
    footprint: { x: 1, z: 1 },
    mass: 1,
    height: 1,
    crewBerths: 20,
  },
  "helm-wheel": {
    type: "helm-wheel",
    kinds: PIRATE,
    category: "command",
    name: "Ship's wheel",
    description:
      "The helm on a quarterdeck · top of its stack · anywhere on deck",
    placement: "grid",
    role: "bridge",
    footprint: { x: 1, z: 2 },
    mass: 0.6,
    height: 1,
  },
  figurehead: {
    type: "figurehead",
    kinds: PIRATE,
    category: "decor",
    name: "Figurehead",
    description: "A carved mermaid at the very front",
    placement: "attach",
    attachTo: "bow-mount",
    allowedPointIds: ["figurehead"],
    mass: 0.1,
    height: 0.8,
    emptyHint: "The figurehead spot is taken",
  },
  "ship-anchor": {
    ...decorDef("ship-anchor", "Anchor", "A heavy iron anchor", 0.5),
    kinds: PIRATE,
  },
  "barrel-stack": {
    ...decorDef("barrel-stack", "Barrels", "Rum, we hope", 0.6),
    kinds: PIRATE,
  },
  "crate-stack": {
    ...decorDef("crate-stack", "Crates", "Stacked supplies", 0.6),
    kinds: PIRATE,
  },
  "treasure-chest": {
    ...decorDef(
      "treasure-chest",
      "Treasure chest",
      "Gold, jewels and a lock",
      0.35
    ),
    kinds: PIRATE,
  },
  rowboat: {
    type: "rowboat",
    kinds: PIRATE,
    category: "lifeboats",
    name: "Rowboat",
    description: "12 seats · hangs from a davit",
    placement: "attach",
    attachTo: "boat-mount",
    mass: 0.2,
    height: 0.4,
    seats: 12,
    emptyHint: "Every davit has a boat — add another davit",
  },
  plank: {
    type: "plank",
    kinds: PIRATE,
    category: "decor",
    name: "Plank",
    description: "Walk it, if you dare · sits on a deck edge",
    placement: "attach",
    attachTo: "edge-mount",
    mass: 0.1,
    height: 0.1,
    emptyHint: "Build a block on an outer edge of the ship",
    holdsEdge: true,
  },
  "pirate-crew": {
    ...decorDef("pirate-crew", "Pirate", "A crewmate with a sword", 1),
    kinds: PIRATE,
  },
  parrot: {
    ...decorDef("parrot", "Parrot", "Squawks quietly", 0.4),
    kinds: PIRATE,
  },
};

export function getPartDef(type: PartType): PartDef {
  return CATALOG[type];
}

export function partsInCategory(category: PartCategory): PartDef[] {
  return PART_TYPES.map((type) => CATALOG[type]).filter(
    (def) => def.category === category
  );
}

/**
 * The parts to list for a ship kind: its own plus the shared ones, or every
 * part when showAll is set. Always in catalog order.
 */
export function visibleParts(kind: ShipKind, showAll: boolean): PartDef[] {
  const defs = PART_TYPES.map((type) => CATALOG[type]);
  return showAll
    ? defs
    : defs.filter((def) => def.kinds === undefined || def.kinds.includes(kind));
}
