import type { ShipKind } from "./kinds";
import {
  PART_TYPES,
  type AttachPointType,
  type PartCategory,
  type PartDef,
  type PartType,
} from "./types";

export const CATEGORIES: readonly { id: PartCategory; name: string }[] = [
  { id: "decks", name: "Decks" },
  { id: "cabins", name: "Cabins" },
  { id: "command", name: "Command" },
  { id: "funnels", name: "Funnels" },
  { id: "masts", name: "Masts" },
  { id: "lifeboats", name: "Lifeboat gear" },
  { id: "naval", name: "Naval" },
  { id: "propulsion", name: "Propulsion" },
  { id: "cargo", name: "Cargo" },
];

export const ATTACH_POINT_LABELS: Record<AttachPointType, string> = {
  "funnel-mount": "deck block with nothing on top",
  "mast-mount": "mast mount",
  "davit-point": "boat-deck edge",
  "boat-mount": "davit",
  "large-funnel-mount": "2×2 of deck blocks with nothing on top",
  "big-boat-mount": "pair of side-by-side davits",
  "prop-mount": "propeller spot under the stern",
  "rudder-mount": "rudder spot under the stern",
  "heli-mount": "helipad with nothing on it",
  "freefall-mount": "freefall boat spot at the stern",
  "edge-mount": "boat-deck edge",
};

/** The 4-wide bridge keeps the original `bridge` id so old saves still load. */
function bridgeDef(type: PartType, width: number): PartDef {
  return {
    type,
    category: "command",
    name: `Bridge · ${width} wide`,
    description: "Forward half, top of its stack",
    placement: "grid",
    role: "bridge",
    footprint: { x: 1, z: width },
    mass: 1,
    height: 1,
  };
}

export const CATALOG: Record<PartType, PartDef> = {
  "deck-1x1": {
    type: "deck-1x1",
    category: "decks",
    name: "Deck block 1×1",
    description: "Superstructure · stacks four high",
    placement: "grid",
    role: "deck",
    footprint: { x: 1, z: 1 },
    mass: 1,
    height: 1,
  },
  "deck-2x1": {
    type: "deck-2x1",
    category: "decks",
    name: "Deck block 2×1",
    description: "Superstructure · stacks four high",
    placement: "grid",
    role: "deck",
    footprint: { x: 2, z: 1 },
    mass: 1,
    height: 1,
  },
  "cabin-1st": {
    type: "cabin-1st",
    category: "cabins",
    name: "First-class cabins",
    description: "30 passengers",
    placement: "grid",
    role: "cabin",
    footprint: { x: 1, z: 1 },
    mass: 1,
    height: 1,
    passengers: { cabinClass: "first", count: 30 },
  },
  "cabin-2nd": {
    type: "cabin-2nd",
    category: "cabins",
    name: "Second-class cabins",
    description: "50 passengers",
    placement: "grid",
    role: "cabin",
    footprint: { x: 1, z: 1 },
    mass: 1,
    height: 1,
    passengers: { cabinClass: "second", count: 50 },
  },
  "cabin-3rd": {
    type: "cabin-3rd",
    category: "cabins",
    name: "Third-class berths",
    description: "120 passengers",
    placement: "grid",
    role: "cabin",
    footprint: { x: 1, z: 1 },
    mass: 1,
    height: 1,
    passengers: { cabinClass: "third", count: 120 },
  },
  "cabin-crew": {
    type: "cabin-crew",
    category: "cabins",
    name: "Crew quarters",
    description: "60 crew berths",
    placement: "grid",
    role: "cabin",
    footprint: { x: 1, z: 1 },
    mass: 1,
    height: 1,
    crewBerths: 60,
  },
  "bridge-3": bridgeDef("bridge-3", 3),
  bridge: bridgeDef("bridge", 4),
  "bridge-5": bridgeDef("bridge-5", 5),
  "bridge-6": bridgeDef("bridge-6", 6),
  "bridge-7": bridgeDef("bridge-7", 7),
  funnel: {
    type: "funnel",
    kinds: ["liner"],
    category: "funnels",
    name: "Funnel",
    description: "Smokestack · sits on a deck block · 40 stokers",
    placement: "attach",
    attachTo: "funnel-mount",
    mass: 2,
    height: 3.2,
    stokers: 40,
    power: 1,
    emptyHint: "Place a deck block with nothing on top of it first",
  },
  mast: {
    type: "mast",
    category: "masts",
    name: "Mast",
    description: "Bow, stern or on top of a deck block",
    placement: "attach",
    attachTo: "mast-mount",
    mass: 0.5,
    height: 7,
    emptyHint: "Every mast spot is taken",
  },
  davit: {
    type: "davit",
    category: "lifeboats",
    name: "Davit",
    description: "Boat-deck edge, on any block",
    placement: "attach",
    attachTo: "davit-point",
    mass: 0.1,
    height: 1,
    emptyHint: "Build a block on an outer edge of the ship",
  },
  "lifeboat-standard": {
    type: "lifeboat-standard",
    category: "lifeboats",
    name: "Lifeboat",
    description: "65 seats · hangs from a davit",
    placement: "attach",
    attachTo: "boat-mount",
    mass: 0.2,
    height: 0.4,
    seats: 65,
    emptyHint: "Every davit has a boat — add another davit",
  },
  "lifeboat-collapsible": {
    type: "lifeboat-collapsible",
    kinds: ["liner"],
    category: "lifeboats",
    name: "Collapsible lifeboat",
    description: "47 seats · hangs from a davit",
    placement: "attach",
    attachTo: "boat-mount",
    mass: 0.2,
    height: 0.4,
    seats: 47,
    emptyHint: "Every davit has a boat — add another davit",
  },
  "funnel-large": {
    type: "funnel-large",
    kinds: ["liner"],
    category: "funnels",
    name: "Large funnel",
    description: "Big smokestack · sits on a 2×2 of deck blocks · 75 stokers",
    placement: "attach",
    attachTo: "large-funnel-mount",
    mass: 4,
    height: 4.2,
    stokers: 75,
    power: 2,
    emptyHint: "Make a 2×2 of deck blocks with nothing on top",
  },
  "lifeboat-large": {
    type: "lifeboat-large",
    kinds: ["liner"],
    category: "lifeboats",
    name: "Large lifeboat",
    description: "150 seats · hangs between two davits",
    placement: "attach",
    attachTo: "big-boat-mount",
    mass: 0.4,
    height: 0.5,
    seats: 150,
    emptyHint: "Put two davits side by side on the same deck edge",
  },
  propeller: {
    type: "propeller",
    category: "propulsion",
    name: "Propeller",
    description: "Mounts under the stern · pushes the ship",
    placement: "attach",
    attachTo: "prop-mount",
    mass: 0.3,
    height: 0.5,
    emptyHint: "Every propeller spot is taken",
  },
  rudder: {
    type: "rudder",
    category: "propulsion",
    name: "Rudder",
    description: "Under the stern · steers the ship",
    placement: "attach",
    attachTo: "rudder-mount",
    mass: 0.2,
    height: 0.9,
    emptyHint: "The rudder spot is taken",
  },
  "turret-small": {
    type: "turret-small",
    kinds: ["navy"],
    category: "naval",
    name: "Gun turret",
    description: "Sits on a deck block · slowly turns",
    placement: "attach",
    attachTo: "funnel-mount",
    mass: 1,
    height: 0.9,
    emptyHint: "Place a deck block with nothing on top of it first",
  },
  "turret-large": {
    type: "turret-large",
    kinds: ["navy"],
    category: "naval",
    name: "Big gun turret",
    description: "Twin guns · sits on a 2×2 of deck blocks",
    placement: "attach",
    attachTo: "large-funnel-mount",
    mass: 2.5,
    height: 1.2,
    emptyHint: "Make a 2×2 of deck blocks with nothing on top",
  },
  "radar-mast": {
    type: "radar-mast",
    kinds: ["navy"],
    category: "naval",
    name: "Radar mast",
    description: "Bow, stern or on top of a deck block · spinning radar",
    placement: "attach",
    attachTo: "mast-mount",
    mass: 0.6,
    height: 6,
    emptyHint: "Every mast spot is taken",
  },
  helipad: {
    type: "helipad",
    kinds: ["navy"],
    category: "naval",
    name: "Helipad",
    description: "Flat pad on a 2×2 of deck blocks",
    placement: "attach",
    attachTo: "large-funnel-mount",
    mass: 1,
    height: 0.15,
    emptyHint: "Make a 2×2 of deck blocks with nothing on top",
  },
  helicopter: {
    type: "helicopter",
    kinds: ["navy"],
    category: "naval",
    name: "Helicopter",
    description: "Lands on a helipad · spinning rotor",
    placement: "attach",
    attachTo: "heli-mount",
    mass: 0.4,
    height: 1,
    emptyHint: "Build a helipad first",
  },
  "rib-boat": {
    type: "rib-boat",
    kinds: ["navy"],
    category: "lifeboats",
    name: "RIB boat",
    description: "15 seats · hangs from a davit",
    placement: "attach",
    attachTo: "boat-mount",
    mass: 0.2,
    height: 0.4,
    seats: 15,
    emptyHint: "Every davit has a boat — add another davit",
  },
  container: {
    type: "container",
    kinds: ["cargo"],
    category: "cargo",
    name: "Container",
    description: "2 TEU · on the main deck or a hatch cover · stacks",
    placement: "grid",
    role: "cargo",
    footprint: { x: 2, z: 1 },
    mass: 0.6,
    height: 1,
    teu: 2,
  },
  "hatch-cover": {
    type: "hatch-cover",
    kinds: ["cargo"],
    category: "cargo",
    name: "Hatch cover",
    description: "Low 2×2 cover over the hold · containers stack on it",
    placement: "grid",
    role: "deck",
    footprint: { x: 2, z: 2 },
    mass: 0.3,
    height: 0.3,
  },
  "cargo-crane": {
    type: "cargo-crane",
    kinds: ["cargo"],
    category: "cargo",
    name: "Cargo crane",
    description: "Sits on a deck block or hatch cover · the jib turns slowly",
    placement: "attach",
    attachTo: "funnel-mount",
    mass: 1,
    height: 2.6,
    emptyHint: "Place a deck block or hatch cover with nothing on top first",
  },
  "lifeboat-freefall": {
    type: "lifeboat-freefall",
    kinds: ["cargo"],
    category: "lifeboats",
    name: "Freefall lifeboat",
    description: "40 seats · slides off the stern",
    placement: "attach",
    attachTo: "freefall-mount",
    mass: 0.5,
    height: 1.2,
    seats: 40,
    emptyHint: "The freefall spot at the stern is taken",
  },
  "cabin-balcony": {
    type: "cabin-balcony",
    kinds: ["cruise"],
    category: "cabins",
    name: "Balcony cabins",
    description: "40 passengers · balconies on outward faces",
    placement: "grid",
    role: "cabin",
    footprint: { x: 1, z: 1 },
    mass: 1,
    height: 1,
    passengers: { cabinClass: "second", count: 40 },
  },
  pool: {
    type: "pool",
    kinds: ["cruise"],
    category: "decks",
    name: "Pool",
    description: "2×2 · sits on blocks or the main deck · nothing builds on it",
    placement: "grid",
    role: "amenity",
    footprint: { x: 2, z: 2 },
    mass: 1,
    height: 0.3,
  },
  waterslide: {
    type: "waterslide",
    kinds: ["cruise"],
    category: "decks",
    name: "Waterslide",
    description: "Sits on a deck block · curls down the side",
    placement: "attach",
    attachTo: "funnel-mount",
    mass: 0.5,
    height: 2.5,
    emptyHint: "Place a deck block with nothing on top of it first",
  },
  "climbing-wall": {
    type: "climbing-wall",
    kinds: ["cruise"],
    category: "decks",
    name: "Climbing wall",
    description: "Sits on a deck block · tall wall with holds",
    placement: "attach",
    attachTo: "funnel-mount",
    mass: 0.5,
    height: 1.8,
    emptyHint: "Place a deck block with nothing on top of it first",
  },
  "lifeboat-enclosed": {
    type: "lifeboat-enclosed",
    kinds: ["cruise"],
    category: "lifeboats",
    name: "Enclosed lifeboat",
    description: "150 seats · hangs from a davit",
    placement: "attach",
    attachTo: "boat-mount",
    mass: 0.3,
    height: 0.5,
    seats: 150,
    emptyHint: "Every davit has a boat — add another davit",
  },
  "raft-canister": {
    type: "raft-canister",
    kinds: ["cruise", "navy"],
    category: "lifeboats",
    name: "Life raft canister",
    description: "25 seats · sits on a boat-deck edge",
    placement: "attach",
    attachTo: "edge-mount",
    mass: 0.1,
    height: 0.4,
    seats: 25,
    emptyHint: "Build a block on an outer edge of the ship",
  },
  "funnel-modern": {
    type: "funnel-modern",
    kinds: ["cruise"],
    category: "funnels",
    name: "Modern funnel",
    description: "Raked diesel stack · sits on a deck block · no stokers",
    placement: "attach",
    attachTo: "funnel-mount",
    mass: 2,
    height: 3.2,
    power: 1,
    emptyHint: "Place a deck block with nothing on top of it first",
  },
  azipod: {
    type: "azipod",
    kinds: ["cruise"],
    category: "propulsion",
    name: "Azipod",
    description: "Steerable pod under the stern · propels and steers",
    placement: "attach",
    attachTo: "prop-mount",
    mass: 0.5,
    height: 0.7,
    emptyHint: "Every propeller spot is taken",
  },
};

export function getPartDef(type: PartType): PartDef {
  return CATALOG[type];
}

export function partsInCategory(category: PartCategory): PartDef[] {
  return PART_TYPES.map((type) => CATALOG[type]).filter(
    (def) => def.category === category
  );
}

/**
 * The parts to list for a ship kind: its own plus the shared ones, or every
 * part when showAll is set. Always in catalog order.
 */
export function visibleParts(kind: ShipKind, showAll: boolean): PartDef[] {
  const defs = PART_TYPES.map((type) => CATALOG[type]);
  return showAll
    ? defs
    : defs.filter((def) => def.kinds === undefined || def.kinds.includes(kind));
}
