version: 2

executors:
  my-executor:
    docker:
      - image: circleci/node:8
    working_directory: /tmp

jobs:
  test-job:
    executor: my-executor
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run Test and Coverage
          command: |
            yarn test --coverage
  build-job:
    executor: my-executor
    branches:
      only:
        - master
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Build the app
          command: |
            yarn build
       - persist_to_workspace:
          root: .
          paths:
            - dist
            - node_modules
  deploy-job:
    docker:
      - image: circleci/node:8
    requires:
      - test-job
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Deploy Master to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN

workflows:
  version: 2
  -deploy:
    jobs:
      - test-job
      - build-job
      - deploy-job:
          requires:
            - test-job
            - build-job
          filters:
            branches:
              only: master
