version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/node:8
    working_directory: ~/project

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run Test and Coverage
          command: yarn test --coverage
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  prod:
    executor: my-executor
    requires:
      - build
    steps:
      - attach_workspace:
          at: ~/project
      - checkout
      - run:
          name: Build the app
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - dist
  deploy:
    executor: my-executor
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Deploy Master to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN

workflows:
 version: 2
 -deploy:
   jobs:
     - build
     - prod
     - deploy:
         requires:
           - build
           - prod
         filters:
           branches:
             only: master

