version: 2.1

executors:
  default:
    docker:
      - image: cypress/base:10
        environment:
          TERM: xterm
    working_directory: ~/project

jobs:
  build:
    executor: default
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: ~/
          paths:
            - project
            - .cache/Cypress
  test-unit-integration:
    executor: default
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Unit/Integration Tests
          command: yarn test --coverage --runInBand
  test-e2e:
    executor: default
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: End To End Tests
          command: yarn test:e2e
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  deploy:
    executor: default
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Build the app
          command: yarn build
      - run:
          name: Display Token
          command: echo $FIREBASE_DEPLOY_TOKEN
      - run:
          name: Deploy Master to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN

workflows:
  Test:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
      - test-unit-integration:
          requires:
            - build
          filters:
            branches:
              ignore:
                - master
      - test-e2e:
          requires:
            - build
          filters:
            branches:
              ignore:
                - master
  Deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - test-unit-integration:
          requires:
            - build
          filters:
            branches:
              only: master
      - test-e2e:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
            - test-unit-integration
            - test-e2e
          filters:
            branches:
              only: master
